name: Survey for Local Language Repository (HINDI)
description: Survey
title: "[Survey Form]: "
assignees:
  - Lingaraj, Shruti, Adarsh
body:
  - type: markdown
    attributes:
      value: |
        # Survey for Local Language Repository
        # -------------------------------------------------
        ## Survey Disclaimer
        ### यह सर्वेक्षण वित्तीय लेन-देन में बहुभाषी चरणों के बारे में जानकारी इकट्ठा करने के लिए होता है। इसका उद्देश्य डेटा और अंतर्दृष्टि लेने के लिए होता है। इसमें भाग लेना स्वैच्छिक है और सभी प्रतिक्रियाएं गोपनीय रहेंगी और केवल शोध उद्देश्यों के लिए उपयोग होगा। और ये सर्वे हमारे अध्ययन के उद्देश्य के लिए लिया है आपका कुछ फायदा के लिए नहीं है
  - type: markdown
    attributes:
      value: |
        # 1. Administrative
  - type: input
    id: name
    attributes:
      label: Name/ Code of surveyor
      description: Enter the name
      placeholder: ex. Lingaraj/Adarsh/Shruti
    validations:
      required: True
  - type: input
    id: location
    attributes:
      label: Location
      description: Where the surveyor taking the survey?
      placeholder: eg. Near Main Gate IIT Madras
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: Start Time
      description: When the survey starts?
      placeholder: e.g. 10.00 AM
    validations:
      required: True
  - type: input
    id: session_count
    attributes:
      label: Session Count / Prior meeting notes
      description: Number of sessions per person
      placeholder: e.g - 1st / 2nd
    validations:
          required: true
  - type: markdown
    attributes:
      value: |
        # 2. Demography / General
  - type: input
    id: name1
    attributes: 
      label: नाम
      description: Name of the person
    validations:
      required: True
  - type: input
    id: age
    attributes:
      label: उम्र
      description: Enter the people age
      placeholder: e.g. 30
    validations:
      required: True
  - type: dropdown
    id: languages
    attributes:
      label: Languages Known
      description: What are the languages know by them
      options:
        - English
        - Hindi
        - Tamil
        - Odia
        - Telugu
        - Bengali
  - type: input
    id: mobile
    attributes:
      label: आप किस तरह का फोन इस्तेमाल कर रहे हैं
      description: Participant is using iOS/Android or (Smartphone / basic keypad phone)
      placeholder: e.g. Smartphone
    validations:
      required: True
  - type: dropdown
    id: mobile1
    attributes:
      label: क्या आपके पास इंटरनेट की सुविधा है
      description: Are they have internet access
      options:
        - "Yes"
        - "No"
    validations:
      required: True
  - type: input
    id: address
    attributes:
      label: आप किस राज्य से हैं
      description: Enter the participant home state
      placeholder: e.g. Odisha
    validations:
      required: True
  - type: dropdown
    id: family_size
    attributes:
      label: आपके दूरस्थ परिवार का आकार क्या है
      description: Enter the participant remote family size
      options:
        - 1-2
        - 2-3
        - 3-4
    validations:
      required: True
  - type: input
    id: education
    attributes:
      label: स्कूली शिक्षा के वर्षों की संख्या
      description: Enter the participant number of years of schooling
      placeholder: e.g. 5th / 8th
    validations:
      required: True
  - type: dropdown
    id: literacy
    attributes:
      label: Digital Literacy
      description: 1. आप प्राथमिक रूप से किस भाषा में संवाद करते हैं? 2. क्या आप संदेश प्राप्त करने में किसी कठिनाई का अनुभव करते हैं? 3. क्या आपको बैंकों से कॉल आती हैं? 4. क्या आपको बैंकों से ओटीपी (वन-टाइम पासवर्ड) जैसे संदेश प्राप्त होते हैं? 5. क्या आप अपने फोन पर सभी संदेशों को पढ़ने और उन तक पहुंचने में सक्षम हैं? 6. आप किस भाषा में संदेश प्राप्त करते हैं? 7. क्या आप अंग्रेजी भाषा में भेजे गए संदेशों को समझ और पढ़ सकते हैं? 8. क्या आप किसी के साथ ओटीपी साझा नहीं करने के महत्व से अवगत हैं?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
  - type: markdown
    attributes:
      value: |
        # 3. Financal Overview
  - type: dropdown
    id: prompt1
    attributes:
      label: आप एक महीने में कितना कमाते हैं
      multiple: false
      options:
        - "< ₹10,000"
        - "₹10,000 -  ₹20,000"
        - "₹20,001 -  ₹30,000"
        - "₹30,001 - ₹40,000"
        - "Above ₹40,000"
    validations:
      required: true

  - type: input
    id: prompt2
    attributes:
      label: आप एक महीने में कितना खर्च करते हैं
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt3
    attributes:
      label: आप एक महीने में अपने परिवार को कितनी राशि भेजते हैं (Remote Family)
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt4
    attributes:
      label: परिवार के अलावा और किसी को कुछ पैसा भेजते हैं?
      placeholder: Enter any additional information
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Investments / निवेश"

  - type: input
    id: prompt5a
    attributes:
      label: a. FD / RD	
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt5b
    attributes:
      label: b. Mutual Funds 				
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt5c
    attributes:
      label: c. Others				
      placeholder: Enter the amount in INR
    validations:
      # required: true
      
  - type: input
    id: prompt5d
    attributes:
      label: d. Others				
      placeholder: Enter the amount in INR
    validations:
      # required: true

  - type: markdown
    attributes:
      value: "## Loans / Liability :"

  - type: input
    id: prompt6a
    attributes:
      label: 1a. Loan Type 	(ऋृण प्रकार)			
      placeholder: Write here
    validations:
      required: true

  - type: input
    id: prompt6b
    attributes:
      label: 1b. Amount			 				
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt6c
    attributes:
      label: 1c. Bank			 				
      placeholder: Write here
    validations:
      required: true

  - type: input
    id: prompt6d
    attributes:
      label: 2a. Loan Type					
      placeholder: Write here
    validations:
      # required: true

  - type: input
    id: prompt6e
    attributes:
      label: 2b. Amount			 				
      placeholder: Enter the amount in INR
    validations:
      # required: true

  - type: input
    id: prompt6f
    attributes:
      label: 2c. Bank			 				
      placeholder: Write here
    validations:
      # required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: | 
         # Banking relationship + Products / Channels.
    validations: 
      required: true
  - type: input
    id: Bank
    attributes:
      label: Bank Account
      description: Number of bank Saving accounts /Post office accounts.
      placeholder: ex. Number
    validations:
      required: true
  - type: input
    id: Bank-detail
    attributes:
      label: Name of Bank
      description: Name of Banks/branch.
      placeholder: ex. SBI
    validations:
      required: true
  - type: markdown
    attributes:
      value: | 
         ## 4. Banking products/services used (multi-choice – includes open list) - Personal usage/awareness?
    validations: 
      required: true
  - type: dropdown
    id: Check-book
    attributes:
      label: Cheque book
      description: Do you have check book?
      multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: dropdown
    id: ATM-Debit
    attributes:
      label: ATM/Debit card
      description: Do you have ATM/Debit card?
      multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: dropdown
    id: Credit-Card
    attributes:
      label: Credit Card
      description: Do you have Credit Card?
      multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: dropdown
    id: Loans
    attributes:
      label: Loans
      description: Have you taken any loans like Gold, Kisan, etc
      multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: Products via branch
      description: Name
    validations:
      required: true
  - type: input
    id: Business
    attributes:
      label: Products via Business correspondent / Bank Mitra, Post office 
      description: Name
    validations:
      required: true
  - type: dropdown
    id: Internet-Banking
    attributes:
      label: Online / Mobile banking.
      description: Are you using Internet banking
      multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: textarea
    id: Others
    attributes:
      label: Others 
      description: Name
    validations:
      # required: true
