name: Survey for Local Language Repository
description: Survey
title: "[Survey Form]: "
assignees:
  - Lingaraj, Shruti, Adarsh
body:
  - type: markdown
    attributes:
      value: |
        # Survey for Local Language Repository
        # -------------------------------------------------
  - type: markdown
    attributes:
      value: |
        # 1. Administrative
  - type: input
    id: name
    attributes:
      label: Name/ Code of surveyor
      description: Enter the name
      placeholder: ex. Lingaraj/Adarsh/Shruti
    validations:
      required: True
  - type: input
    id: location
    attributes:
      label: Location
      description: Where the surveyor taking the survey?
      placeholder: eg. Near Main Gate IIT Madras
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: Start Time
      description: When the survey starts?
      placeholder: e.g. 10.00 AM
    validations:
      required: True
  - type: input
    id: session_count
    attributes:
      label: Session Count / Prior meeting notes
      description: Number of sessions per person
      placeholder: e.g - 1st / 2nd
    validations:
          required: true
  - type: markdown
    attributes:
      value: |
        # 2. Demography / General
  - type: input
    id: name1
    attributes: 
      label: Name
      description: Name of the person
    validations:
      required: True
  - type: input
    id: age
    attributes:
      label: Age
      description: Enter the people age
      placeholder: e.g. 30
    validations:
      required: True
  - type: dropdown
    id: gender
    attributes:
      label: Gender
      options:
        - Male
        - Female
        - Other
    validations:
      required: True
  - type: dropdown
    id: languages
    attributes:
      label: Languages Known
      description: What are the languages know by them
      options:
        - English
        - Hindi
        - Tamil
        - Odia
        - Telugu
        - Bengali
      multiple: True
    validations:
      required: True
  - type: input
    id: mobile
    attributes:
      label: Phone make / model
      description: Participant is using iOS/Android or (Smartphone / basic keypad phone)
      placeholder: e.g. Smartphone
    validations:
      required: True
  - type: dropdown
    id: mobile1
    attributes:
      label: Mobile Data/Internet Access
      description: Are they have internet access
      options:
        - "Yes"
        - "No"
    validations:
      required: True
  - type: input
    id: address
    attributes:
      label: Home State?
      description: Enter the participant home state
      placeholder: e.g. Odisha
    validations:
      required: True
  - type: dropdown
    id: family_size
    attributes:
      label: Remote family size
      description: Enter the participant remote family size
      options:
        - 1-2
        - 2-3
        - 3-4
    validations:
      required: True
  - type: input
    id: education
    attributes:
      label: Number of years of schooling
      description: Enter the participant number of years of schooling
      placeholder: e.g. 5th / 8th
    validations:
      required: True
  - type: dropdown
    id: literacy
    attributes:
      label: Digital Literacy
      description: 1. What Language do you primarily communicate in ?     2. Do you experience any difficulties in receiving messages?       3. Do you receive calls from banks?    4. Do you receive messages from banks, such as OTPs (One-Time Passwords)?       5. Are you able to read and access all the messages on your phone?       6. In which language do you receive messages?         7. Can you understand and read messages sent in the English language?           8. Are you aware of the importance of not sharing OTPs with anyone? 
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
    validations:
      required: True
  - type: markdown
    attributes:
      value: |
        # 3. Financal Overview
  - type: dropdown
    id: prompt1
    attributes:
      label: Monthly Income
      multiple: false
      options:
        - "< ₹10,000"
        - "₹10,000 -  ₹20,000"
        - "₹20,001 -  ₹30,000"
        - "₹30,001 - ₹40,000"
        - "Above ₹40,000"
    validations:
      required: true

  - type: input
    id: prompt2
    attributes:
      label: Local Monthly Expense
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt3
    attributes:
      label: Typical Fund Transferred per Month to Remote Family
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt4
    attributes:
      label: Any Other Financial Notes (Open)
      placeholder: Enter any additional information
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Investments"

  - type: input
    id: prompt5a
    attributes:
      label: a. FD / RD		
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt5b
    attributes:
      label: b. Mutual Funds 				
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt5c
    attributes:
      label: c. Others				
      placeholder: Enter the amount in INR
    validations:
      # required: true
      
  - type: input
    id: prompt5d
    attributes:
      label: d. Others				
      placeholder: Enter the amount in INR
    validations:
      # required: true

  - type: markdown
    attributes:
      value: "## Loans / Liability :"

  - type: input
    id: prompt6a
    attributes:
      label: 1a. Loan Type					
      placeholder: Write here
    validations:
      required: true

  - type: input
    id: prompt6b
    attributes:
      label: 1b. Amount			 				
      placeholder: Enter the amount in INR
    validations:
      required: true

  - type: input
    id: prompt6c
    attributes:
      label: 1c. Bank			 				
      placeholder: Write here
    validations:
      required: true

  - type: input
    id: prompt6d
    attributes:
      label: 2a. Loan Type					
      placeholder: Write here
    validations:
      # required: true

  - type: input
    id: prompt6e
    attributes:
      label: 2b. Amount			 				
      placeholder: Enter the amount in INR
    validations:
      # required: true

  - type: input
    id: prompt6f
    attributes:
      label: 2c. Bank			 				
      placeholder: Write here
    validations:
      # required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: | 
         # Banking relationship + Products / Channels.
    validations: 
      required: true
  - type: input
    id: Bank
    attributes:
      label: Bank Account
      description: Number of bank Saving accounts /Post office accounts.
      placeholder: ex. Number
    validations:
      required: true
  - type: input
    id: Bank-detail
    attributes:
      label: Name of Bank
      description: Name of Banks/branch.
      placeholder: ex. SBI
    validations:
      required: true
  - type: markdown
    attributes:
      value: | 
         ## 4. Banking products/services used (multi-choice – includes open list) - Personal usage/awareness?
    validations: 
      required: true
  - type: dropdown
    id: Check-book
    attributes:
      label: Cheque book
      description: Do you have check book?
      multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: dropdown
    id: ATM-Debit
    attributes:
      label: ATM/Debit card
      description: Do you have ATM/Debit card?
      multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: dropdown
    id: Credit-Card
    attributes:
      label: Credit Card
      description: Do you have Credit Card?
      multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: dropdown
    id: Loans
    attributes:
      label: Loans
      description: Have you taken any loans like Gold, Kisan, etc
      multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: Products via branch
      description: Name
    validations:
      required: true
  - type: input
    id: Business
    attributes:
      label: Products via Business correspondent / Bank Mitra, Post office 
      description: Name
    validations:
      required: true
  - type: dropdown
    id: Internet-Banking
    attributes:
      label: Online / Mobile banking.
      description: Are you using Internet banking
      multiple: true
      options:
        - "Yes"
        - "No"
        - Prefer not to say
        - I do not say
    validations:
      required: true
  - type: textarea
    id: Others
    attributes:
      label: Others 
      description: Name
    validations:
      # required: true
  - type: markdown
    attributes:
      value: | 
         # Payments and Transfers (Monthly / Annual)
    validations: 
      required: true
  - type: textarea
    id: upi
    attributes:
      label: UPI or UPI enabled apps
      description: You are using any UPI apps?
      placeholder:  BHIM
    validations:
      required: true
  - type: input
    id: wallets
    attributes:
      label: Used Wallets
      description: You are using wallets?
      placeholder:  Yes / No
    validations:
      required: true
  - type: input
    id: counts
    attributes:
      label:   Typical Count of Local Payments per month (in proximity / phone number, UPI-handle etc.)
      description: Number of counts
      placeholder:  Number
    validations:
      required: true
  - type: input
    id: Local-payment
    attributes:
      label: Typical amount for Local payments
      description: Approx amount using through UPI
      placeholder:  "10,000"
    validations:
      required: true
  - type: input
    id: QR
    attributes:
      label: QR Code based Payments
      description: Are you making payment through QR code?
      placeholder:  Yes / No
    validations:
      required: true
  - type: input
    id: rent
    attributes:
      label: Rent
      description: You have your own house / you are living in Rent
      placeholder:  Yes / No
    validations:
      required: true
  - type: dropdown
    id: Transport
    attributes:
      label: Local Transport
      description: Which type of local transport you are using?
      multiple: true
      options:
        - Metro
        - Train
        - Bus
        - Others
    validations:
      required: true
  - type: markdown
    attributes:
      value: | 
         ## Other BBPS list:
    validations: 
      required: true
  - type: input
    id: recharge
    attributes:
      label: Phone / data Recharge
      description: Are you using UPI for recharge payments?
      placeholder:  Yes / No
    validations:
      required: true
  - type: input
    id: Electricity
    attributes:
      label: Electricity / Water / Utilities
      description: Are you using UPI for Electricity / Water bills payments?
      placeholder:  Yes / No
    validations:
      required: true
  - type: input
    id: othe
    attributes:
      label: Others
      description: Are you using UPI for other payments?
      placeholder:  Yes / No
    validations:
      required: true
  - type: dropdown
    id: remote
    attributes:
      label: Remote payments / fund transfers
      description: Are you using UPI payments for remote payments?
      multiple: true
      options:
        - Wallet
        - UPI
        - NEFT/IMPS/RTGS
        - Other Method
    validations:
      required: true
