name: Sample Form
description: This is a sample form
title: "[Sample]: "
labels: ["bug", "triage"]
assignees:
  - Lingaraj
body:
  - type: markdown
    attributes:
      value: |
        This is a sample form

