name: Survey Form of Local Repository app 
description: This is a sample form
title: "[FORM] <Sample>"
body:
- type: input
  id: name
  attributes:
    label: Name
    description: Name / Code of Surveyor
    placeholder: Enter your name
   validations:
    required: True   
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
