name: Sample Form
description: This is a sample form
title: "[Sample]: "
labels: ["bug", "triage"]
assignees:
  - Lingaraj
body:
  - type: markdown
    attributes:      
    value: |
        This is a sample form
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
