name: Sample Form
description: This is a sample form
title: "[FORM] <Sample>"
body:
- type: checkboxes
  attributes:
    label: XYZABCD
    description: Please give the answer.
    options:
    - label: Option 1
    - label: Option 2
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
