name: Local Language Repository Survey
description: It is a financial survey on UPI Apps.
title: "[Survey on Financial Challenges]: "
labels: ["survey", "UPI"]
assignees:
  - lingaraj
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  -type: input
    attributes:
      label: Please input here
