name: Local Language Repo Survey
description: Here is the simple financial survey 
labels: ABCDE
assignees:
  - lingaraj,Adarsh, Shruti
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Survey Form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type : checkboxes
    id: Options_13
    attributes:
      label: Choose any option from here
      description: Here is the example of checkbox 
      options:
        label: Option1
        label: Option2
        required: true
