name: Survey for Local Language Repository
description: Survey
title: "[Survey Form]: "
labels: ["bug", "triage"]
assignees:
  - Lingaraj, Shruti, Adarsh
body:
  - type: markdown
    attributes:
      value: |
        This survey contains 6 sections
  - type: input
    id: name
    attributes:
      label: Name/ Code of surveyor
      description: Enter the name
      placeholder: ex. Lingaraj/Adarsh/Shruti
    validations:
      required: True
  - type: input
    id: location
    attributes:
      label: Location
      description: Where the surveyor taking the survey?
      placeholder: eg. Near Main Gate IIT Madras
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: Start Time
      description: When the survey starts?
      placeholder: e.g. 10.00 AM
  - type: input
    id: session_count
    attributes:
      label: Session Count / Prior meeting notes
      description: Number of sessions per person
      placeholder: e.g - 1st / 2nd
    validations:
          required: true
  - type: markdown
    attributes:
      value: |
        2. Demograohy / General
  
