name: Survey for Local Language Repository
description: Survey
title: "[Survey Form]: "
labels: ["bug", "triage"]
assignees:
  - Lingaraj, Shruti, Adarsh
body:
  - type: markdown
    attributes:
      value: |
        # 1. Administrative
  - type: input
    id: name
    attributes:
      label: Name/ Code of surveyor
      description: Enter the name
      placeholder: ex. Lingaraj/Adarsh/Shruti
    validations:
      required: True
  - type: input
    id: location
    attributes:
      label: Location
      description: Where the surveyor taking the survey?
      placeholder: eg. Near Main Gate IIT Madras
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: Start Time
      description: When the survey starts?
      placeholder: e.g. 10.00 AM
    validations:
      required: True
  - type: input
    id: session_count
    attributes:
      label: Session Count / Prior meeting notes
      description: Number of sessions per person
      placeholder: e.g - 1st / 2nd
    validations:
          required: true
  - type: markdown
    attributes:
      value: |
        # 2. Demography / General
  - type: input
    id: name1
    attributes: 
      label: Name
      description: Name of the person
    validations:
      required: True
  - type: input
    id: age
    attributes:
      label: Age
      description: Enter the people age
      placeholder: e.g. 30
    validations:
      required: True
  - type: dropdown
    id: gender
    attributes:
      label: Age
      options:
        - Male
        - Female
        - Other
    validations:
      required: True
  - type: input
    id: mobile
    attributes:
      label: Phone make / model
      description: Participant is using iOS/Android or (Smartphone / basic keypad phone)
      placeholder: e.g. Smartphone
    validations:
      required: True
  - type: dropdown
    id: mobile1
    attributes:
      label: Mobile Data/Internet Access
      description: Are they have internet access
      options:
        - "Yes"
        - "No"
    validations:
      required: True
