name: Survey for Local Language Repository
description: Survey
title: "[Survey Form]: "
labels: ["bug", "triage"]
assignees:
  - Lingaraj, Shruti, Adarsh
body:
  - type: markdown
    attributes:
      value: |
        This survey contains 6 sections
  - type: input
    id: name
    attributes:
      label: Name/ Code of surveyor
      description: Enter the name
      placeholder: ex. Lingaraj/Adarsh/Shruti
    validations:
      required: True
  - type: input
    id: location
    attributes:
      label: Location
      description: Where the surveyor taking the survey?
      placeholder: eg. Near Main Gate IIT Madras
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
