# .github/workflows/main.yml
name: Survey for Local Language Repository
run-name : Local Language 2023 Github Actions
on:
  push:
    branches:
      - master

jobs:
  submit_to_neo4j:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install neo4j

    - name: Run Python script
      run: python submit.py
      env:
        NEO4J_URI: ${{ secrets.NEO4J_URI }}
        NEO4J_USER: ${{ secrets.NEO4J_USER }}
        NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        INPUT_NAME: ${{ github.event.inputs.name }}
        INPUT_DATE_TIME: ${{ github.event.inputs.date_time }}
        INPUT_LOCATION: ${{ github.event.inputs.location }}
        INPUT_TIME: ${{ github.event.inputs.time }}
        INPUT_SESSION_COUNT: ${{ github.event.inputs.session_count }}
        # Add other input variables
